##import libraries
```{r}
library(ggplot2)
library(DESeq2)
library(EnhancedVolcano)
`%>%` <- dplyr::`%>%`
library(pheatmap)
library(ggpubr)
library(biomaRt)
library(ggrepel)
```

##load datafiles
```{r}
load("consensus_peaks.mRp.clN.dds.rld.RData") ##nextflow-atac output with default parameters; datafile available at dbGAP repository associated with this manuscript

topgenes = read.table("~/bindetect_results.txt", stringAsFactor = FALSE, h=TRUE) ##output file from TOBIAS using default parameters
```

##Preprocessing to remove samples (biological replicates) that did not pass depth and peak filters (see Methods in manuscript)
```{r}
atac_data <- dds[, -6]
atac_data <- atac_data[, -6]
atac_data <- atac_data[, -2]
atac_data <- atac_data[,-10]
atac_data <- atac_data[,-14]
atac_data <- atac_data[,-14]

keep <- rowSums(counts(atac_data) ==0) <=7
dds <- b[keep,]
rld <- rlog(dds)

pcaData <- plotPCA(rld, intgroup=c("condition"), returnData=TRUE)

percentVar <- round(100 * attr(pcaData, "percentVar"))

##PCA plot for Fig5F
ggplot(pcaData, aes(PC1, PC2, color=group)) + geom_point(size=5) +   xlab(paste0("PC1: ",percentVar[1],"% variance")) +   ylab(paste0("PC2: ",percentVar[2],"% variance")) + coord_fixed() + labs(color = "Polarity") + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), aspect.ratio = 1, axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_text(size = 20, face = "bold"), legend.title = element_text(size = 15, face = "bold"), legend.text = element_text(size = 12, face = "bold")) + scale_color_manual(values = c("#D95F02", "#1B9E77"))
```

##processing of chromatin accessibility regions
```{r}
rld.assay <- assay(rld)
dds_object <- DESeq(dds)
deseq_results <- results(dds_object, contrast = c("condition", "abnormal", "normal"))
deseq_df <- deseq_results %>% as.data.frame() %>% tibble::rownames_to_column(var = "Gene")
deseq_df %>%dplyr::arrange(dplyr::desc(stat))
deseq_signif_peak <- deseq_df %>% dplyr::filter(pvalue <= 0.01) %>% dplyr::pull(Gene)

mat <- rld.assay[deseq_signif_peak,]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(rld))
df = subset(anno, select= -c(sizeFactor, replaceable))
ann_colors = list(condition = c(normal="#1B9E77", abnormal="#D95F02"))

##heatmap for chromatin accessibility regions; Fig5D
p <- pheatmap(mat, annotation_col = df, annotation_names_row = FALSE, annotation_names_col = TRUE, clustering_method = "single", col = colorRampPalette(c("navy", "white", "firebrick3"))(50), annotation_colors = ann_colors, show_colnames = FALSE, show_rownames = FALSE, treeheight_col = 15, treeheight_row = 15) 
```

##processing of transcription footprinting data output by TOBIAS
```{r}
changelimit = 0.07
pvallimit = 80

topgenes$diffexpressed <- rep("NO",length(topgenes$abnormal_normal_change))
topgenes$diffexpressed[topgenes$abnormal_normal_change > changelimit & -log10(topgenes$abnormal_normal_pvalue) > pvallimit] <- "UP"
topgenes$diffexpressed[topgenes$abnormal_normal_change < -changelimit & -log10(topgenes$abnormal_normal_pvalue) > pvallimit] <- "DOWN"
topgenes$labels <- rep(NA,length(topgenes$abnormal_normal_change))
topgenes$labels[topgenes$diffexpressed != "NO"] <- topgenes$name[topgenes$diffexpressed != "NO"]
topgenes$labels2 <- rep(NA, length(topgenes$abnormal_normal_change))
topgenes$labels2[grep("SP1_MA0079.5", topgenes$output_prefix)] = "SP1"
topgenes$labels2[grep("SP2_MA0516.3", topgenes$output_prefix)] = "SP2"
topgenes$labels2[grep("SP3_MA0746.2", topgenes$output_prefix)] = "SP3"
topgenes$labels2[grep("SP4_MA0685.2", topgenes$output_prefix)] = "SP4"
topgenes$labels2[grep("SP8_MA0747.1", topgenes$output_prefix)] = "SP8"
topgenes$labels2[grep("SP9_MA1564.1", topgenes$output_prefix)] = "SP9"

topgenes$diffexpressed <- as.factor(topgenes$diffexpressed)

##plot differential binding of TFs; Fig5G
p <-ggplot(data=topgenes, aes(x=abnormal_normal_change, y=-log10(abnormal_normal_pvalue),label=labels2)) + 
    geom_point(aes(colour = topgenes$diffexpressed))+ 
    theme_classic() + 
    geom_text_repel(max.overlaps = Inf,show.legend = FALSE,size = 3.5, box.padding = 0.8,  min.segment.length = 0) + 
    scale_colour_manual(values=c("red","grey","blue")) +
    geom_vline(xintercept=c(-changelimit, changelimit),linetype = "dashed",  alpha=0.4) +
    geom_hline(yintercept=pvallimit, linetype = "dashed", alpha=0.4)  +
    theme(axis.text.y = element_text(size = 15),axis.text.x = element_text(size = 15),axis.title=element_text(size=18), aspect.ratio =1) + 
    labs(x ="Change", y = expression("Significance (-Log[10])")) + 
    expand_limits(x=c(-0.2,0.2))
```

